### ISSUE TITLE
/home/runner/MusicBot/node_modules/gcommands/src/base/GCommandsClient.js:25         if (!options.loader?.cmdDir) throw new GError('[DEFAULT OPTIONS]', 'You must specify the cmdDir');                             ^  SyntaxError: Unexpected token '.'     at wrapSafe (internal/modules/cjs/loader.js:915:16)     at Module._compile (internal/modules/cjs/loader.js:963:27)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)     at Module.load (internal/modules/cjs/loader.js:863:32)     at Function.Module._load (internal/modules/cjs/loader.js:708:14)     at Module.require (internal/modules/cjs/loader.js:887:19)     at require (internal/modules/cjs/helpers.js:74:18)     at Object.<anonymous> (/home/runner/MusicBot/node_modules/gcommands/src/index.js:5:22)     at Module._compile (internal/modules/cjs/loader.js:999:30)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### ISSUE THREAD

**Issue by AviaJae** [Garlic-Team/MusicBot#6]
So im having this error right now in replit

/home/runner/MusicBot/node_modules/gcommands/src/base/GCommandsClient.js:25
        if (!options.loader?.cmdDir) throw new GError('[DEFAULT OPTIONS]', 'You must specify the cmdDir');
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/MusicBot/node_modules/gcommands/src/index.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    
    I cannot seem to understand what is this error because i never seen it before

**Comment by xhyrom** [comment]
You need download old version of gcommands

**Comment by xhyrom** [comment]
npm i gcommnds@5.2.5
